### ISSUE TITLE
[BUG] Trucker Job Towing Issues

### ISSUE THREAD

**Issue by Quagel** [dennrick/LineageRoleplay#91]
## [BUG REPORT]

**Describe the bug** *(A clear and detailed description of what the bug is):*
Two similar issues while conducting the new trucker job related to issues hauling different loads.
Gas Tank Trailer: Had issues hauling with the Phantom, gas tank trailer would scrape along the road causing damage and loss in pay. Unsure if other trucks produce the same issue.
Logs Trailer: Had issues hauling the log load from the logging site with the Hauler. Log load was very heavy and could not get the truck moving without revving to max RPM. Max speeds while hauling were significantly slower than others ~25-30mph on flat and coming to a stop on slight inclines. My truck was slightly damaged (not major) at the time so unsure if this played an impact at all. Unsure if other trucks produce the same issue.

**To Reproduce** *(Steps to reproduce the behavior):*
  Gas Tank Trailer: 1) Attach to Phantom 2) if noticeable sparking from back of trailer it is dragging.
  Log Load Trailer: 1) Attach to Hauler 2) Check if starting/max speed is acceptable. 3) If needed check with slight wear/damage 
    to truck

**Expected behavior** *(A clear and concise description of what you expected to happen):*
  Various trailers should move similar and not damage while driving regardless of the truck attached to.

**Video Clip of the Issue Happening** *(If applicable, add a link or links to a clip showing the bug to help explain your proble):*
    
    N/A

**Additional context** *(Add any other context about the problem here):*
    
   Have had no issues hauling the container truck from ship yard and construction truck load from Harmony area.
    
**Screenshots** *(If applicable, add screenshots to help explain your problem):*
   
    N/A

**Comment by MjrDeathAdder** [comment]
Resolved in next hotfix

**Comment by daddyDUBZ** [comment]
10:20 PM] drunkpilot: --This is the beginning of the trucking issue ticket. All trucking script issues should be placed here--
[10:22 PM] drunkpilot: Ticket #1 Maple Syrup Controls
OldCdnGamer — 05/30/2021
BUG!!!
[11:05 PM]
So when I finish the trucking and I click N at the end to stop and return to office the Get Next Delivery action is still present and can't be removed.  If I was to press Y for cruise control it would then send me to the next Pickup.

May 31, 2021

MjrDeathAdder — 05/31/2021
Not sure why this is happening i thought kt got patched. Are you using controller at all? You can always go back to the depot anyways

OldCdnGamer — 05/31/2021
Hey @MjrDeathAdder I am not using controller strictly keyboard 
June 20, 2021

MjrDeathAdder — 06/20/2021
I'm puzzled as to why this is happening I'll have a look into the issue when I have some spare time
It's a tough one as I personally don't have the issue to be able to confirm

OldCdnGamer — 06/20/2021
I will try another truck run next time I am as my Big Maple char and see if the issue still persists.  Maybe an update lately might have fixed something.  I will let you know here once I do the test.(edited)
June 24, 2021

--Back and forth on if this hyas been tested

OldCdnGamer — 07/01/2021
Just tested it again and did a run and I pressed N and still see Get Next Delivery and it didn't seem to accept the entry.  I drove down the road a bit and it disappeared.  Not instance response of selection it looks like. @Accidont(edited)


kraKen — 07/01/2021
did you check f8 for errors?

Dennrick — 07/01/2021
I've confirmed this is not functioning in the PTR with no F8 errors.


Dr.BirdBath — 07/11/2021
I just checked this in the live server my "n" dosent not work either but my PTT does
@OldCdnGamer if you changed you talk muscle it should be that one to end the job

MjrDeathAdder — 07/12/2021
Ah if anything else is bound to that key it's not longer responsive
[11:38 AM]
For this script

OldCdnGamer — 07/12/2021
I will try it next time I am in with my civ char.
July 15, 2021

drunkpilot — Today at 9:54 PM
@OldCdnGamer have you tried this again?
[10:37 PM] drunkpilot: -- Ticket 2 -- TazJosh
[10:37 PM] drunkpilot: TazJosh | Khan Eljannah — Today at 10:00 PM
720 there's a trailer that i cannot attach to every time i do the pickup/delivery at the milk farm when i go to deliver the trailer i cop a % fine on the damage after trying to load the trailer up is there anyway we can move the trailer or adjust it so it wont be as difficult to load on to a big rig?
